<?xml version="1.0"?>
<package format="3">
  <name>gpu_ros_managed_ros</name>
  <version>0.1.0</version>
  <description>Small intra-process managed publisher/subscriber wrappers.</description>
  <maintainer email="unnamets@gmail.com">Boshen Chen</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
