add_executable(gpu_ros_managed_core_test core_test.cpp)
target_link_libraries(gpu_ros_managed_core_test PRIVATE gpu_ros_managed_core)
target_compile_features(gpu_ros_managed_core_test PRIVATE cxx_std_17)
target_compile_options(gpu_ros_managed_core_test PRIVATE -Wall -Wextra -Wpedantic)
add_test(NAME gpu_ros_managed_core_test COMMAND gpu_ros_managed_core_test)
