build:
  base-paths:
    - src/gpu_ros_managed/gpu_ros_managed_core
    - src/gpu_ros_managed/gpu_ros_managed_cuda
    - src/gpu_ros_managed/gpu_ros_managed_ros
    - src/gpu_ros_managed/gpu_ros_managed_tensor_list
    - src/amd_ros_object_detection/migrated_packages
    - src/amd_ros_object_detection/isaac_ros_object_detection/isaac_ros_yolov8
  cmake-args:
    - -DCMAKE_BUILD_TYPE=Release
    - -DORT_ENABLE_CUDA=ON
    - -DORT_ENABLE_ROCM=OFF
    - -DORT_ENABLE_MIGRAPHX=OFF
    - -DBUILD_NITROS_TRANSPORT=ON
    - -DBUILD_TESTING=ON
  symlink-install: true
test:
  base-paths:
    - src/gpu_ros_managed/gpu_ros_managed_core
    - src/gpu_ros_managed/gpu_ros_managed_cuda
    - src/gpu_ros_managed/gpu_ros_managed_ros
    - src/gpu_ros_managed/gpu_ros_managed_tensor_list
    - src/amd_ros_object_detection/migrated_packages
  packages-select:
    - gpu_ros_managed_core
    - gpu_ros_managed_cuda
    - gpu_ros_managed_ros
    - gpu_ros_managed_tensor_list
    - isaac_ros_onnx_inference
