<?xml version="1.0"?>
<package format="3">
  <name>isaac_ros_yolov8_std</name>
  <version>0.1.0</version>
  <description>YOLOv8 image encoder and decoder using standard ROS2 TensorList messages</description>

  <maintainer email="maintainer@example.com">Maintainer</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>isaac_ros_tensor_list_interfaces</depend>
  <depend>libopencv-dev</depend>
  <depend>isaac_ros_detection_common</depend>
  <depend>gpu_ros_managed_core</depend>
  <depend>gpu_ros_managed_hip</depend>
  <depend>gpu_ros_managed_ros</depend>
  <depend>gpu_ros_managed_tensor_list</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <test_depend>launch_testing_ament_cmake</test_depend>
  <test_depend>python3-onnx</test_depend>
  <test_depend>isaac_ros_test</test_depend>
  <test_depend>isaac_ros_onnx_inference</test_depend>
  <test_depend>isaac_ros_image_proc</test_depend>
  <test_depend>isaac_ros_tensor_proc</test_depend>
  <test_depend>sensor_msgs</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
